version: '3'
services:
  credito-card-backend:
    image: juliosilvacwb/credito-card-backend
    container_name: card-backend-v1
    ports:
      - "8080:8080"
    networks: 
      - net-card
  credito-card-frontend:
    image: juliosilvacwb/credito-card-frontend
    container_name: card-frontend-v1
    ports:
      - "4200:4200"
    networks: 
      - net-card
    depends_on: 
      - "credito-card-backend"

networks: 
  net-card: 
    driver: bridge    